version: "3.6"

services:
  riverstart_db:
    image: postgres:11
    container_name: riverstart_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=riverstart
    networks:
      - riverstart-network
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data

  riverstart_site:
    image: riverstart:latest
    container_name: riverstart_site
    environment:
      - C_FORCE_ROOT='true'
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=riverstart
      - DB_HOST=riverstart_db
      - DEBUG=False
    depends_on:
      - riverstart_db
    networks:
      - riverstart-network
    ports:
      - 41088:8000
    volumes:
      - ${SITE_PATH}:/app
    command: ./entrypoint.sh

networks:
  riverstart-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}