# Generated by Django 3.1 on 2020-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('publish', models.BooleanField(blank=True, default=False, verbose_name='Publish product')),
                ('delete', models.BooleanField(blank=True, default=False, verbose_name='Deleted product')),
                ('category', models.ManyToManyField(related_name='products', to='main.Category', verbose_name='Category')),
            ],
        ),
    ]
